name: Jaswant Networking

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  build-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install backend deps
        working-directory: networking-backend
        run: npm ci

      - name: Lint backend
        working-directory: networking-backend
        run: npm run lint -- --max-warnings=0

      - name: Install frontend deps
        working-directory: networking-frontend
        run: npm ci

      - name: Lint frontend
        working-directory: networking-frontend
        run: npm run lint -- --max-warnings=0

      - name: Build backend Docker image
        run: docker build -t backend ./networking-backend

      - name: Build frontend Docker image
        run: docker build -t frontend ./networking-frontend
